### ISSUE TITLE
Can this direct message a user when someone comments on their PR?

### ISSUE THREAD

**Issue by clarkd** [lfilho/bitbucket-slack-pr-hook#18]
As per the title, our users want to receive a Slack message (via bot/direct message) when someone else comments on their PR - rather than everything in a single channel.

Can this be achieved with this?

**Comment by lfilho** [comment]
Not as the code stands right now, no.
But I imagine it shouldn't be hard to accomplish, assuming we can accomplish this via Slack's api (it's been a very long time since I stopped actively developing for Slack API so I don't know).

Assuming the API allows, I suppose it would be a matter of sending the message to the user handle instead of the channel handle.

But that would also mean you'd have to map the usernames in Bitbutcket to the usernames on Slack...

Hope it helps. Feel free to submit a PR ;)
