### ISSUE TITLE
Published docker container

### ISSUE THREAD

**Issue by passcod** [lfilho/bitbucket-slack-pr-hook#5]
Given that all the options are passed through the env, it would be great if this was published on hub.docker.com that way we could just pull the docker image instead of building it ourselves.

**Comment by lfilho** [comment]
Great idea! Would you like to help me with that?

**Comment by passcod** [comment]
I don't quite see how. The process to put up an image on the docker hub is
to have an account there, then set up an "automated build" pointing at the
repo. It requires a hook to be set up on the source repo, hence can only be
done by the repo owner.

**Comment by lfilho** [comment]
@passcod After long time, I've come back to this repo and am closing the issues and PRs.
It's is published in Docker Hub!
https://hub.docker.com/r/lfilho/bitbucket-slack-pr-hook/

Could you please test it? Since it's an automated build, I'm assuming it works, so I'm closing this issue.

Feel free to reopen it if you have any problems.

**Comment by passcod** [comment]
I'm on holiday, but will test as soon as I'm back! :)
